#!/bin/bash
./script/cmake-build simulation -DOT_WAKEUP_COORDINATOR=ON -DOT_WAKEUP_END_DEVICE=ON -DOT_FULL_LOGS=ON -DOT_CHANNEL_MONITOR=OFF -DOT_CHANNEL_MANAGER=OFF -DOT_CSL_RECEIVER=ON -DOT_BUILD_GTEST=OFF -DOT_CSL_PEER=ON "$@"
