#!/bin/bash
./script/cmake-build simulation -DOT_LOG_OUTPUT=PLATFORM_DEFINED -DOT_LOG_LEVEL=DEBG -DOT_LOG_MAX_SIZE=1024 -DBUILD_TESTING=OFF -DOT_CLI_LOG=ON -DOT_CHANNEL_MONITOR=OFF -DOT_CHANNEL_MANAGER=OFF
