#!/bin/bash
./script/cmake-build simulation -DOT_LOG_OUTPUT=PLATFORM_DEFINED -DOT_LOG_LEVEL=DEBG -DOT_BUILD_GTEST=OFF -DOT_BUILD_UTEST=OFF -DOT_CHANNEL_MONITOR=OFF -DOT_CHANNEL_MANAGER=OFF -DOT_WAKEUP_COORDINATOR=ON -DOT_WAKEUP_END_DEVICE=ON -DOT_CSL_RECEIVER=ON -DOT_PEER_TO_PEER=ON "$@"
