
source "_common.exp"

set wc "wc"
set dataset "0e080000000000010000000300001635060004001fffe002083ae7ad5bd2c958ef0708fd77c6ccf72ab5230510cceb51a2f1602439b0343c07d6ca981f030f4f70656e5468726561642d363834660102684f0410116d23d1b996bd75d25bdc911aa33fb40c0402a0f7f8"


# WC
spawn_node $wc

send_user "Switch to WC:\n"

#send "extaddr dead00beef00caf2\n"
#expect_line "Done"

#send "wakeup channel 22\n"
#expect_line "Done"

send "dataset set active $dataset\n"
expect_line "Done"

send "mode\n"
expect_line "Done"

send "routerselectionjitter 1\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"


wait_for "state" "leader"

sleep 0.5

#send "wakeup wake dead00beef00caf1 7500 1090\n"
send "wakeup wake  ffffffffffffffff 7500 1090\n"
#expect_line "Done"

sleep 2

#send "ping fe80:0:0:0:dcad:be:ef00:caf1\n"
#expect_line "Done"

#send "ping fe80:0:0:0:dcad:be:ef00:caf1\n"
#expect_line "Done"

#sleep 2

interact
