
source "_common.exp"

set wed "wed"
set dataset "0e080000000000010000000300001635060004001fffe002083ae7ad5bd2c958ef0708fd77c6ccf72ab5230510cceb51a2f1602439b0343c07d6ca981f030f4f70656e5468726561642d363834660102684f0410116d23d1b996bd75d25bdc911aa33fb40c0402a0f7f8"


# WED
spawn_node $wed

send_user "Switch to WED:\n"

#send "wakeup channel 22\n"
#expect_line "Done"

#send "extaddr dead00beef00caf1\n"
#expect_line "Done"

sleep 1

send "dataset set active $dataset\n"
expect "Done"

send "mode\n"
expect_line "Done"

send "mode -\n"
expect_line "Done"

send "pollperiod 2500\n "
expect "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"

send "wakeup wed enable\n"
expect_line "Done"

interact
