
# Show Log:
# tail -f  /var/log/syslog | grep ot-cli > log.txt
# sed -i -r 's/.{66}//' ./log.txt && vim log.txt
#

source "_common.exp"

set wc 1
set wed 2
set dataset "0e080000000000010000000300001635060004001fffe002083ae7ad5bd2c958ef0708fd77c6ccf72ab5230510cceb51a2f1602439b0343c07d6ca981f030f4f70656e5468726561642d363834660102684f0410116d23d1b996bd75d25bdc911aa33fb40c0402a0f7f8"


# WC
spawn_node $wc

# WED
spawn_node $wed

#-----------------------------WED------------------------------------
switch_node $wed
send_user "Switch to WED:\n"

send "extaddr dead00beef00caf1\n"
expect_line "Done"

send "dataset set active $dataset\n"
expect "Done"

send "mode -\n"
expect_line "Done"

send "csl period 640000\n"
expect_line "Done"

send "csl timeout 10\n"
expect_line "Done"

send "childsupervision checktimeout 10\n"
expect "Done"

send "childsupervision interval 2\n"
expect "Done"

send "pollperiod 200000\n "
expect "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"

sleep 1

send "s2s sample start\n"
expect_line "Done"

send "s2s listen start\n"
expect_line "Done"
#-----------------------------WC-------------------------------------

switch_node $wc
send_user "Switch to WC:\n"

send "dataset set active $dataset\n"
expect_line "Done"

send "mode dn\n"
expect_line "Done"

send "csl period 640000\n"
expect_line "Done"

send "csl timeout 10\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"

sleep 0.5

send "s2s connect dead00beef00caf1\n"
expect_line "Done"

#-----------------------------WED------------------------------------

switch_node $wed
send_user "Switch to WED:\n"

wait_for "state" "child"
expect_line "Done"

send "state\n"
expect_line "Done"

send "parent\n"
expect_line "Done"

send "ipaddr\n"
expect_line "Done"

#-----------------------------WC------------------------------------

switch_node $wc
send_user "Switch to WC:\n"

send "state\n"
expect_line "Done"

send "child table\n"
expect_line "Done"

send "ping fe80:0:0:0:dcad:be:ef00:caf1\n"
expect_line "Done"

send "ping fe80:0:0:0:dcad:be:ef00:caf1\n"
expect_line "Done"

send "ping fe80:0:0:0:dcad:be:ef00:caf1\n"
expect_line "Done"

send "ping fe80:0:0:0:dcad:be:ef00:caf1\n"
expect_line "Done"

interact
