#!/usr/bin/expect -f
#
#                   WC -- WED
#
log_file test.log
source "tests/scripts/expect/_common.exp"
source "tests/scripts/expect/_multinode.exp"

set WC  1
set WED 2
set WAKEUP_ID "dead0000beef0000cafe"

send_user ">>> setup WED\n"
spawn_node $WED

setup_default_network

send "mode -\n"
expect_line "Done"

#send "csl period 1000000\n"
#expect_line "Done"

#send "csl timeout 10\n"
#expect_line "Done"

send "extaddr deadbeefcafe0001\n"
expect_line "Done"

send "pollperiod 2500\n"
expect "Done"

send "ifconfig up\n"
expect_line "Done"

send "wakeup channel 11\n"
expect_line "Done"

send "wakeup parameters 1000000 8000\n"
expect_line "Done"

send "wakeup wakeupid add $WAKEUP_ID\n"
expect_line "Done"

send "wakeup listen enable\n"
expect_line "Done"



send_user ">>> setup WC\n"
spawn_node $WC
setup_default_network
send "ifconfig up\n"
expect_line "Done"

send "wakeup channel 11\n"
expect_line "Done"

send_user ">>> WC wakes up WED\n"
send "wakeup wake $WAKEUP_ID 7500 1090\n"

switch_node $WED
expect_line "Wakeup Frame Received: deadbeefcafe0001"

interact
