#!/usr/bin/expect -f
#
# Test topology:
#
# WC1 (FED) <------> (WED , SSED) <----------> LEADER (FTD)
#
# Test Steps:
# <1> Setup LEADER and wait for it becoming a leader
# <1> Setup WED as a thread sleepy child and wait for the WED becoming a child
# <2> Setup WC1
# <3> WC1 establishs a P2P link with WED
# <4> WED pings WC1
# <5> WC1 checks the registered SRP server hosts
# <6> WC1 tears down the P2P link form WED
#

log_file test.log

source "tests/scripts/expect/_common.exp"
source "tests/scripts/expect/_multinode.exp"

set WC1 1
set LEADER 2
set WED 3
set wc1_ext_address "deadbeefcafe0001"
set leader_ext_address "deadbeefcafe0002"
set wed_ext_address "deadbeefcafe0003"
set WAKEUP_ID "dead0000beef0000cafe"

#-----------------------------LEADER-------------------------------------
send_user "\n\n>>> setup LEADER\n"
spawn_node $LEADER

setup_default_network

send "childsupervision checktimeout 20\n"
expect "Done"

send "childsupervision interval 10\n"
expect "Done"

send "pollperiod 200000\n "
expect "Done"

send "extaddr $leader_ext_address\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"

wait_for "state" "leader"

#-----------------------------WED-------------------------------------
send_user "\n\n>>> setup WED\n"
spawn_node $WED

setup_default_network

send "mode -\n"
expect_line "Done"

send "csl period 640000\n"
expect_line "Done"

send "csl timeout 10\n"
expect_line "Done"

send "childsupervision checktimeout 20\n"
expect "Done"

send "childsupervision interval 10\n"
expect "Done"

send "pollperiod 200000\n "
expect "Done"

send "extaddr $wed_ext_address\n"
expect_line "Done"

send "wakeup channel 11\n"
expect_line "Done"

send "wakeup parameters 1000000 8000\n"
expect_line "Done"

send "wakeup wakeupid add $WAKEUP_ID\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"

wait_for "state" "child"

send "ipaddr\n"
expect_line "Done"

send "wakeup listen enable\n"
expect_line "Done"

set wed_link_local_addr [get_ipaddr linklocal]

send "srp client host name wed\n"
expect_line "Done"

send "srp client host address $wed_link_local_addr\n"
expect_line "Done"

send "srp client service add ins1 _matter._tcp 5540\n"
expect_line "Done"

send "srp client autostart enable\n"
expect_line "Done"

#-----------------------------WC1-------------------------------------

send_user "\n\n>>> Setup WC1\n"
spawn_node $WC1
setup_default_network

send "mode rdn\n"
expect_line "Done"

send "extaddr $wc1_ext_address\n"
expect_line "Done"

send "routerupgradethreshold 0\n"
expect_line "Done"

send "wakeup channel 11\n"
expect_line "Done"

send "srp server faststart enable\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

#send "thread start\n"
#expect_line "Done"

set wc1_link_local_addr [get_ipaddr linklocal]

send_user "\n\n>>> WC1 establishs a P2P link with WED\n"

send "p2p connect id $WAKEUP_ID 7500 1090\n"
expect_line "Done"

send "ping $wed_link_local_addr\n"
expect_line "Done"

sleep 2

#-----------------------------WED-------------------------------------
send_user "\n\n>>> WED pings WC1\n"

switch_node $WED
#
send "ipaddr\n"
expect_line "Done"

send "ping $wc1_link_local_addr\n"
expect_line "Done"

sleep 2

#-----------------------------WC1-------------------------------------
send_user "\n\n>>> WC1 checks all registered srp server hosts \n"
switch_node $WC1

send "srp server state\n"
expect_line "Done"

send "srp server host\n"
expect_line "Done"


send_user "\n\n>>> WC1 tears down the P2P link form WED \n"

send "p2p disconnect $wed_ext_address\n"
expect_line "Done"

sleep 2
