#!/usr/bin/expect -f
#
#                      Leader
#                      /    \
#                   SSED1  SSED2
#                     \     / \
#                      \   /   \
#                       WED1  WED2
source "tests/scripts/expect/_common.exp"
source "tests/scripts/expect/_multinode.exp"

set LEADER 1
set SSED1 2
set SSED2 3
set WED1 4
set WED2 5

send_user ">>> setup leader\n"
spawn_node $LEADER
setup_default_network
attach "leader"


send_user ">>> setup SSED1\n"
spawn_node $SSED1
setup_default_network
run_command "mode -"
run_command "csl period 1000000"
run_command "csl timeout 10"
attach "child"
set ssed1_extaddr [get_extaddr]
set ssed1_lladdr [get_ipaddr linklocal]


send_user ">>> setup SSED2\n"
spawn_node $SSED2
setup_default_network
run_command "mode -"
run_command "csl period 1000000"
run_command "csl timeout 10"
attach "child"
set ssed2_extaddr [get_extaddr]
set ssed2_lladdr [get_ipaddr linklocal]


send_user ">>> setup leader topology\n"
switch_node $LEADER
run_command "macfilter addr add $ssed1_extaddr"
run_command "macfilter addr add $ssed2_extaddr"
run_command "macfilter addr allowlist"


send_user ">>> setup WED1\n"
spawn_node $WED1
setup_default_network
run_command "mode -"
run_command "csl period 1000000"
run_command "csl timeout 10"
run_command "ifconfig up"
run_command "wakeup channel 11"
run_command "wakeup parameters 1000000 8000"
run_command "wakeup listen enable"
run_command "macfilter addr add $ssed1_extaddr"
run_command "macfilter addr add $ssed2_extaddr"
run_command "macfilter addr allowlist"
set wed1_lladdr [get_ipaddr linklocal]
set wed1_extaddr [get_extaddr]
run_command "srp client host name wed1"
run_command "srp client host address $wed1_lladdr"
run_command "srp client service add ins1 _matter._tcp 5540"


send_user ">>> setup WED2\n"
spawn_node $WED2
setup_default_network
run_command "mode -"
run_command "csl period 1000000"
run_command "csl timeout 10"
run_command "ifconfig up"
run_command "wakeup channel 11"
run_command "wakeup parameters 1000000 8000"
run_command "wakeup listen enable"
run_command "macfilter addr add $ssed2_extaddr"
run_command "macfilter addr allowlist"
set wed2_lladdr [get_ipaddr linklocal]
set wed2_extaddr [get_extaddr]
run_command "srp client host name wed2"
run_command "srp client host address $wed2_lladdr"
run_command "srp client service add ins2 _matter._tcp 5540"


send_user ">>> SSED1 wake up WED1\n"
switch_node $SSED1
run_command "srp server addrmode anycast"
run_command "srp server enable"
run_command "wakeup wake $wed1_extaddr 7500 1090"
sleep 5
run_command "srp server state"
run_command "netstat"

switch_node $WED1
run_command "srp client start $ssed1_lladdr 53"
sleep 15

switch_node $SSED1
run_command "srp server host" "$wed1_lladdr"
run_command "ping $wed1_lladdr"


switch_node $WED1
run_command "wakeup listen enable"

switch_node $SSED2
run_command "srp server addrmode anycast"
run_command "srp server enable"
send_user ">>> SSED2 wake up WED1\n"
run_command "wakeup wake $wed1_extaddr 7500 1090"
sleep 5
run_command "ping $wed1_lladdr"

switch_node $SSED1
send_user ">>> SSED1 should continue to be able to reach WED1\n"
run_command "ping $wed1_lladdr"

send_user ">>> SSED2 wake up WED2\n"
switch_node $SSED2
run_command "wakeup wake $wed2_extaddr 7500 1090"
sleep 5
run_command "ping $wed2_lladdr"
