#!/usr/bin/expect -f
#
# Test topology:
#
# WC1 (SSED) <------> WED (SSED)
#
# Test Steps:
# <1> Setup WED
# <2> Setup WC1
# <3> WC1 establishs a P2P link with WED
# <4> WED pings WC1
# <5> WED tears down the P2P link form WC1
#

log_file test.log

source "tests/scripts/expect/_common.exp"
source "tests/scripts/expect/_multinode.exp"

set WC1 1
set WED 3
set wc1_ext_address "deadbeefcafe0001"
set wed_ext_address "deadbeefcafe0003"
set WAKEUP_ID "dead0000beef0000cafe"

#-----------------------------WED-------------------------------------
send_user "\n\n>>> setup WED\n"
spawn_node $WED

setup_default_network

send "mode -\n"
expect_line "Done"

send "csl period 640000\n"
expect_line "Done"

send "csl timeout 10\n"
expect_line "Done"

send "childsupervision checktimeout 20\n"
expect "Done"

send "childsupervision interval 10\n"
expect "Done"

send "pollperiod 200000\n "
expect "Done"

send "extaddr $wed_ext_address\n"
expect_line "Done"

send "wakeup channel 11\n"
expect_line "Done"

send "wakeup parameters 1000000 8000\n"
expect_line "Done"

send "wakeup wakeupid add $WAKEUP_ID\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

#send "thread start\n"
#expect_line "Done"

send "ipaddr\n"
expect_line "Done"

send "wakeup listen enable\n"
expect_line "Done"

set wed_link_local_addr [get_ipaddr linklocal]

#-----------------------------WC1-------------------------------------

send_user "\n\n>>> Setup WC1\n"
spawn_node $WC1
setup_default_network

send "mode -\n"
expect_line "Done"

send "csl period 640000\n"
expect_line "Done"

send "csl timeout 10\n"
expect_line "Done"

send "childsupervision checktimeout 20\n"
expect "Done"

send "childsupervision interval 10\n"
expect "Done"

send "pollperiod 200000\n "
expect "Done"

send "extaddr $wc1_ext_address\n"
expect_line "Done"

send "routereligible disable\n"
expect_line "Done"

send "wakeup channel 11\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

#send "thread start\n"
#expect_line "Done"

set wc1_link_local_addr [get_ipaddr linklocal]

send_user "\n\n>>> WC1 establishs a P2P link with WED\n"

send "p2p connect id $WAKEUP_ID 7500 1090\n"
expect_line "Done"

#-----------------------------WED-------------------------------------
send_user "\n\n>>> WED pings WC1\n"

switch_node $WED

send "ipaddr\n"
expect_line "Done"

send "ping $wc1_link_local_addr\n"
expect_line "Done"

sleep 1

send_user "\n\n>>> WED tears down the P2P link form WC1 \n"

send "p2p disconnect $wc1_ext_address\n"
expect_line "Done"

sleep 2
