#!/usr/bin/expect -f
#
#  Copyright (c) 2025, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

source "tests/scripts/expect/_common.exp"

set CSL_TRANSMITTER 1
set CSL_RECEIVER    2

send_user "\n\n>>> Setup CSL Transmitter\n"
spawn_node $CSL_TRANSMITTER

setup_default_network
attach "leader"
set csl_transmitter_ip [get_ipaddr mleid]

send_user "\n\n>>> Setup CSL Receiver\n"
spawn_node $CSL_RECEIVER

send "mode -\n"
expect_line "Done"

send "csl period 320000\n"
expect_line "Done"

send "csl timeout 10\n"
expect_line "Done"

send "childsupervision checktimeout 20\n"
expect "Done"

send "childsupervision interval 10\n"
expect "Done"

send "pollperiod 200000\n "
expect "Done"

setup_default_network
attach "child"
set csl_receiver_ip [get_ipaddr mleid]

#send_user "\n\n>>> Ping CSL Transmitter\n"
#send "ping $csl_transmitter_ip 20 5\n"
#for {set i 1} {$i <= 5} {incr i} {
#    expect "28 bytes from $csl_transmitter_ip: icmp_seq=$i"
#}

switch_node $CSL_TRANSMITTER

send_user "\n\n>>> Ping CSL Receiver\n"
send "ping $csl_receiver_ip 20 5\n"
for {set i 1} {$i <= 5} {incr i} {
    expect "28 bytes from $csl_receiver_ip: icmp_seq=$i"
}
